runtime: nodejs10

instance_class: F2

handlers:
  - url: /images/(.*)
    static_files: build/images/\1
    upload: build/images/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)
  - url: /(.*\.(json|png|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|png|ico|js)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20

automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: 2

liveness_check:
  path: "/build"
  timeout_sec: 4
  check_interval_sec: 30
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 200
