runtime: nodejs10

instance_class: F2

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20
  

automatic_scaling:
  min_instances: 1
  max_instances: 6
  min_idle_instances: 1
  max_idle_instances: 5  

liveness_check:
  path: "/public"
  timeout_sec: 4
  check_interval_sec: 30
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 200
